container scan

diff --git a/.github/workflows/commit-stage.yml b/.github/workflows/commit-stage.yml
--- a/.github/workflows/commit-stage.yml
+++ b/.github/workflows/commit-stage.yml
@@ -31,5 +31,22 @@ jobs:
     - name: Build with Gradle Wrapper
       run: ./gradlew build
 
+    - name: Anchore Container Scan
+      uses: anchore/scan-action@v3.6.4
+      id: scan
+      with:
+        # The path to scan. This option is mutually exclusive with "image" and "sbom".
+        path: "${{ github.workspace }}"
+        # Set to false to avoid failing based on severity-cutoff. Default is to fail when severity-cutoff is reached (or surpassed)
+        fail-build: true
+        severity-cutoff: high
+        acs-report-enable: true
+
+    - name: Upload vulnerability report
+      uses: github/codeql-action/upload-sarif@v3
+      if: success() || failure()
+      with:
+        sarif_file: ${{ steps.scan.outputs.sarif }}
+
     - name: Run tests
       run: ./gradlew test
